name: GymManagement
version: 1.3
main: us.hqgaming.gymmanagement.GymManagement
author: Xeno
description: 
         A gym plugin made by Xeno from HQGaming.us
commands:
  badges:
    description: Displays badges
  badge:
    description: Badge Commands
  gym:
    description: Gym Commands
  gyms:
    description: Gym Commands
permissions:
  badge.see:
    default: op
    description: Allows a player to see others badges
  badge.remove:
    default: op
    description: Allows a player to remove others badges
  badge.give:
    default: op
    description: Allows a player to give others badges